/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JPanel;
/**
 *
 * @author Burak
 */
public class CourseAnalys extends javax.swing.JFrame {
   
    public static ArrayList<String> arr; 
    public static String id;
    /**
     * Creates new form NewJFrame
     * //@param first
     * //@param second
     * //@param third
     * @param a 
     * @return  
     */
    public static ArrayList<String> array(ArrayList<String> a) {
        arr = a;
        System.out.println(arr);
        String lastIndex = arr.get(arr.size()-2);
        //arr.remove(lastIndex);
        System.out.println(arr);
        return arr;
    }
    public CourseAnalys() {
        init();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        kGradientPanel1.setkEndColor(new java.awt.Color(144, 87, 81));
        kGradientPanel1.setkGradientFocus(1100);
        kGradientPanel1.setkStartColor(new java.awt.Color(100, 104, 99));
        kGradientPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Here is the list of courses that ");
        kGradientPanel1.add(jLabel2);
        jLabel2.setBounds(120, 30, 320, 50);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("You have take in total :");
        kGradientPanel1.add(jLabel3);
        jLabel3.setBounds(240, 77, 250, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Res/BackArrow.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        kGradientPanel1.add(jLabel4);
        jLabel4.setBounds(30, 30, 40, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 953, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(967, 617));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:7
        Welcome.main();
        this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void arr() {
        JLabel a;
        JPanel p;
        int count = 0;
        int x = 400;
        int y = 150;
        Color col = null;
        for(int i = 0; i<arr.size(); i++) {
            count++;            
        }
        String[] myArray = new String[count];
        for(int k = 0; k<arr.size(); k++) {
            myArray[k] = arr.get(k);
        } 
        int index = 2;
        for(int j = 0; j< myArray.length; j++) {        
              if(myArray[index].equals("fail")) {
                  if(myArray[j].equals("fail") || myArray[j].equals("pass") || myArray[j].equals(id)) {
                      
                  } else {
                p = new JPanel();
                p.setBounds(x, y, 250, 32);
                p.setBackground(new Color(204, 41, 0));
                a = new JLabel();
                a.setText(myArray[j]);
                a.setFont(new Font("Segoe UI", 0, 18));
                a.setForeground(new Color(255, 255, 255));
                a.setBounds(x, y, 250, 30);
                p.add(a);
                kGradientPanel1.add(p);
                y=y+35; 
                  }
                   if(j == index) {
                      if(index + 3 < count) {
                         index = index + 3;
                      } 
            }
            } else if(myArray[index].equals("pass")) {
                  if(myArray[j].equals("faill") || myArray[j].equals("pass") || myArray[j].equals(id)) {
                      
                  } else {
                p = new JPanel();
                p.setBounds(x, y, 250, 32);
                p.setBackground(new Color(0, 153, 0));
                a = new JLabel();
                a.setText(myArray[j]);
                a.setFont(new Font("Segoe UI", 0, 18));
                a.setForeground(new Color(255, 255, 255));
                a.setBounds(x, y, 250, 30);
                p.add(a);
                kGradientPanel1.add(p);
                y=y+35;
           }
                if(j == index) {
                     if(index + 3 < count) {
                        index = index + 3;
                      } 
            }
            }
      }
    }
    @SuppressWarnings(value = "unchecked")
    public void init() {
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        
        kGradientPanel1.setkEndColor(new java.awt.Color(144, 87, 81));
        kGradientPanel1.setkGradientFocus(1100);
        kGradientPanel1.setkStartColor(new java.awt.Color(100, 104, 99));
        kGradientPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Here is the list of courses that ");
        kGradientPanel1.add(jLabel2);
        jLabel2.setBounds(120, 30, 320, 50);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); 
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("You have took in total :");
        kGradientPanel1.add(jLabel3);
        jLabel3.setBounds(200, 75, 250, 40);
        
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Res/BackArrow.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        kGradientPanel1.add(jLabel4);
        jLabel4.setBounds(30, 30, 40, 30);
        arr();
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 953, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
        );
        
        setSize(new java.awt.Dimension(967, 617));
        setLocationRelativeTo(null);
    } // </editor-fold>

    /**
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CourseAnalys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CourseAnalys().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public keeptoo.KGradientPanel kGradientPanel1;
    // End of variables declaration//GEN-END:variables
}
