/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project;
/**
 *
 * @author Burak
 */
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class Welcome extends javax.swing.JFrame {
    static String name;
    static String id;
    /**
     * Creates new form NewJFrame
     */ 
    public Welcome() {
        initComponents();       
    }
    public static void id(String id) {
        Welcome.id = id;
    }
    public static void Name(String name) {
        Welcome.name = name;
    } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jPanel1 = new javax.swing.JPanel();
        rSButton3 = new rojeru_san.RSButton();
        rSButton4 = new rojeru_san.RSButton();
        rSButton6 = new rojeru_san.RSButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        kGradientPanel1.setkEndColor(new java.awt.Color(144, 87, 81));
        kGradientPanel1.setkGradientFocus(1100);
        kGradientPanel1.setkStartColor(new java.awt.Color(100, 104, 99));
        kGradientPanel1.setLayout(null);

        jPanel1.setOpaque(false);

        rSButton3.setBackground(new java.awt.Color(100, 104, 99));
        rSButton3.setText("Course Analys");
        rSButton3.setColorHover(new java.awt.Color(144, 87, 81));
        rSButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSButton3MouseClicked(evt);
            }
        });

        rSButton4.setBackground(new java.awt.Color(100, 104, 99));
        rSButton4.setText("Attendance");
        rSButton4.setColorHover(new java.awt.Color(144, 87, 81));
        rSButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSButton4MouseClicked(evt);
            }
        });

        rSButton6.setBackground(new java.awt.Color(100, 104, 99));
        rSButton6.setText("Course Enrollment");
        rSButton6.setColorHover(new java.awt.Color(144, 87, 81));
        rSButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSButton6MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome " + name + "!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 45, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rSButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rSButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rSButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(123, 123, 123))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(rSButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(rSButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(rSButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(306, Short.MAX_VALUE))
        );

        kGradientPanel1.add(jPanel1);
        jPanel1.setBounds(0, 0, 330, 580);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 953, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(967, 617));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rSButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButton4MouseClicked
        // TODO add your handling code here: 
        try { 
            Class.forName("com.mysql.cj.jdbc.Driver"); 
            Connection con = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/test?serverTimezone=UTC&user=root&password=1234");             
            Statement statement = con.createStatement();                      
            String b = "SELECT * FROM attendances where StudentID =" + id;
            ResultSet rs = statement.executeQuery(b);
            ResultSetMetaData md = rs.getMetaData();
            int col = md.getColumnCount();
            ArrayList<String> arr = new ArrayList<>();
            while(rs.next()) {                      
                for(int j = 3; j<=col; j++) {
                   String first = rs.getString(j);
                    if(first.equals(rs.getString("attendances.attendance"))){
                        if(Integer.parseInt(first) > 14) {
                            first = "NA";
                        }
                    }
                   arr.add(first);
                }                       
            }
                AttendanceFrame.main();
                AttendanceFrame.array(arr);
                this.dispose();  
        } catch(HeadlessException | ClassNotFoundException | SQLException e) {
            JOptionPane.showConfirmDialog(null, "An error accured while establishing connection");
        }   
    }//GEN-LAST:event_rSButton4MouseClicked

    private void rSButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButton3MouseClicked
        // TODO add your handling code here:
         try { 
            Class.forName("com.mysql.cj.jdbc.Driver"); 
            Connection con = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/test?serverTimezone=UTC&user=root&password=1234");
            Statement statement = con.createStatement();                      
            String b = "SELECT * FROM courses where ID =" + id;
            ResultSet rs = statement.executeQuery(b);
            ResultSetMetaData md = rs.getMetaData();
            int col = md.getColumnCount();
            ArrayList<String> arr = new ArrayList<>();
            Color color = null;
            while(rs.next()) {           
                for(int j = 1; j<=col; j++) {               
                   String first = rs.getString(j);
                   arr.add(first);
                }
            }
                CourseAnalys.main();
                CourseAnalys.array(arr);  
                CourseAnalys.id = id;
                this.dispose();
        } catch(HeadlessException | ClassNotFoundException | SQLException e) {
            JOptionPane.showConfirmDialog(null, "An error accured while establishing connection");
        }
    }//GEN-LAST:event_rSButton3MouseClicked

    private void rSButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButton6MouseClicked
        // TODO add your handling code here:
        //CourseEnrollment.main();
        //this.dispose();
    }//GEN-LAST:event_rSButton6MouseClicked
     
    /**
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Welcome().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private rojeru_san.RSButton rSButton3;
    private rojeru_san.RSButton rSButton4;
    private rojeru_san.RSButton rSButton6;
    // End of variables declaration//GEN-END:variables
}
