/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import java.util.ArrayList;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author aeren
 */
public class AdminEkrani extends javax.swing.JDialog {

    DefaultTableModel model;
    OgrenciIslemleri islemler=new OgrenciIslemleri();
    
    /**
     * Creates new form AdminEkrani
     * @param parent
     * @param modal
     */
    public AdminEkrani(java.awt.Frame parent, boolean modal) {
        
        super(parent, modal);
        initComponents();
        model= (DefaultTableModel)ogrenci_tablosu.getModel();
        ogrenciGoruntule();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ogrenci_tablosu = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        arama_cubugu = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ad_alani = new javax.swing.JTextField();
        soyad_alani = new javax.swing.JTextField();
        bolum_alani = new javax.swing.JTextField();
        mesaj_yazisi = new javax.swing.JLabel();
        ogrenciEkle = new javax.swing.JButton();
        guncelle_butonu = new javax.swing.JButton();
        ogrenci_sil = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        ogrenci_tablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "ad", "soyad", "bölüm"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ogrenci_tablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ogrenci_tablosuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ogrenci_tablosu);
        if (ogrenci_tablosu.getColumnModel().getColumnCount() > 0) {
            ogrenci_tablosu.getColumnModel().getColumn(0).setResizable(false);
            ogrenci_tablosu.getColumnModel().getColumn(2).setResizable(false);
        }

        arama_cubugu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arama_cubuguActionPerformed(evt);
            }
        });
        arama_cubugu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                arama_cubuguKeyReleased(evt);
            }
        });

        jLabel1.setText("Ad:");

        jLabel2.setText("Soyad:");

        jLabel3.setText("Bölüm:");

        mesaj_yazisi.setForeground(new java.awt.Color(255, 51, 51));

        ogrenciEkle.setText("Yeni Öğrenci Ekle");
        ogrenciEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ogrenciEkleActionPerformed(evt);
            }
        });

        guncelle_butonu.setText("Öğrenci Güncelle");
        guncelle_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guncelle_butonuActionPerformed(evt);
            }
        });

        ogrenci_sil.setText("Öğrenci Sil");
        ogrenci_sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ogrenci_silActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(arama_cubugu, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(34, 34, 34)
                        .addComponent(ad_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(146, 146, 146)
                        .addComponent(ogrenciEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(soyad_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(146, 146, 146)
                        .addComponent(guncelle_butonu, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(bolum_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(146, 146, 146)
                        .addComponent(ogrenci_sil, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(mesaj_yazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(arama_cubugu, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(ad_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ogrenciEkle))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(soyad_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(guncelle_butonu))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(bolum_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ogrenci_sil))
                .addGap(11, 11, 11)
                .addComponent(mesaj_yazisi)
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(958, 633));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void arama_cubuguKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_arama_cubuguKeyReleased
        // TODO add your handling code here:
        String ara=(String)arama_cubugu.getText();
        dinamikAra(ara);
    }//GEN-LAST:event_arama_cubuguKeyReleased

    private void ogrenciEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ogrenciEkleActionPerformed
        // TODO add your handling code here:
        mesaj_yazisi.setText("");
        
        String ad=ad_alani.getText();
        String soyad=soyad_alani.getText();
        String bolum=bolum_alani.getText();
        
        islemler.ogrenciEkle(ad,soyad,bolum);
        
        ogrenciGoruntule();
        mesaj_yazisi.setText("Yeni Öğrenci Başarıyla Eklendi...");
        
        
    }//GEN-LAST:event_ogrenciEkleActionPerformed

    private void ogrenci_tablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ogrenci_tablosuMouseClicked
        // TODO add your handling code here:
        int selectedrow=ogrenci_tablosu.getSelectedRow();
        
        ad_alani.setText(model.getValueAt(selectedrow,1).toString());
        soyad_alani.setText(model.getValueAt(selectedrow,2).toString());
        bolum_alani.setText(model.getValueAt(selectedrow,3).toString());
        
        
    }//GEN-LAST:event_ogrenci_tablosuMouseClicked

    private void ogrenci_silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ogrenci_silActionPerformed
        
        mesaj_yazisi.setText("");
        
        int selectedRow=ogrenci_tablosu.getSelectedRow();
        
        if(selectedRow==-1){
            if(model.getRowCount()==0){
                mesaj_yazisi.setText("Çalışan tablosu şu anda boş...");
            }
            else {
                
                mesaj_yazisi.setText("Çalışan Başarıyla Silindi...");
            }
            
        }
        else {
                int id=(int) model.getValueAt(selectedRow,0);
                islemler.ogrenciSil(id);
                
                ogrenciGoruntule();
                mesaj_yazisi.setText("Öğrenci başarıyla silindi..");
                
            }
        
        
    }//GEN-LAST:event_ogrenci_silActionPerformed

    private void guncelle_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guncelle_butonuActionPerformed
        // TODO add your handling code here:
        String ad=ad_alani.getText();
        String soyad=soyad_alani.getText();
        String bolum=bolum_alani.getText();
        
        int selectedRow= ogrenci_tablosu.getSelectedRow();
        
        if(selectedRow==-1){
            if(model.getRowCount()==0){
                mesaj_yazisi.setText("Öğrenci Tablosu şu anda boş..");
            }
            else {
                mesaj_yazisi.setText("Lütfen güncellenecek bir öğrenci seçin.");
            }
        }
        else {
            int id=(int)model.getValueAt(selectedRow, 0);
            
            islemler.ogrenciGuncelle(id,ad, soyad, bolum);
            ogrenciGoruntule();
            
            mesaj_yazisi.setText("Öğrenci başarıyla güncellendi");
        }
        
    }//GEN-LAST:event_guncelle_butonuActionPerformed

    private void arama_cubuguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arama_cubuguActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arama_cubuguActionPerformed
    public void dinamikAra(String ara){
        TableRowSorter<DefaultTableModel> tr=new TableRowSorter<DefaultTableModel>(model);
        
        ogrenci_tablosu.setRowSorter(tr);
        
        
        tr.setRowFilter(RowFilter.regexFilter(ara));
    }
    /**
     */
    public void ogrenciGoruntule(){
        
        model.setRowCount(0);
        
        ArrayList<Ogrenci> ogrenciler=new ArrayList<Ogrenci>();
        
        ogrenciler=islemler.ogrencileriGetir();
        
        if(ogrenciler!=null){
            
            for(Ogrenci ogrenci:ogrenciler){
                Object[] eklenecek={ogrenci.getId(),ogrenci.getAd(),ogrenci.getSoyad(),ogrenci.getBolum()};
                
                model.addRow(eklenecek);
            }
            
            
        }              
    } 
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            AdminEkrani dialog = new AdminEkrani(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ad_alani;
    private javax.swing.JTextField arama_cubugu;
    private javax.swing.JTextField bolum_alani;
    private javax.swing.JButton guncelle_butonu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel mesaj_yazisi;
    private javax.swing.JButton ogrenciEkle;
    private javax.swing.JButton ogrenci_sil;
    private javax.swing.JTable ogrenci_tablosu;
    private javax.swing.JTextField soyad_alani;
    // End of variables declaration//GEN-END:variables
}
